tasks:
  - before: sdk install java 17.0.4.1-tem < /dev/null
  - init: ./mvnw --version && ./mvnw install -DskipTests=false

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-java-pack
