tasks:
  - init: sdk install java 17.0.4.1-tem < /dev/null && ./mvnw --version

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-maven
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-java-pack
